version: '3.1'

services:
  mariadb:
    image: mariadb:11.6
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my-database
      MYSQL_USER: my-user
      MYSQL_PASSWORD: my-pw
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
